---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: post-vol
  namespace: psql
  labels:
    type: local
    app: postgresql
spec:
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteMany

