apiVersion: postgresql.example.com/v1alpha1
kind: PgBackup
metadata:
  name: example-pgbackup
spec:
  image: applicadb/postgres-python 
  serviceIp: service.psql.svc.cluster.local
  dbName: books;students;employes;supermarket
  postgresDb: postgresdb
  postgresUser: postgresadmin
  postgresPassword: admin123
  backupFile: data.sql
  schedule: "*/1 * * * * "
